Feature/add item
olehkril/gl-java-mentorship-july-2022 pull request #1
Opened 2022-07-13 09:28 UTC by rudik-byte

2022-07-15 08:26 UTC, olehkril requested changes

2022-07-18 09:50 UTC, rudik-byte commented on src/main/java/com/global/inbox/controller/TestController.java
> +package com.global.inbox.controller;
done

2022-07-18 09:51 UTC, rudik-byte commented on src/main/java/com/global/inbox/model/Item.java
> +package com.global.inbox.model;
What do you mean?

2022-07-18 09:51 UTC, rudik-byte commented on src/main/java/com/global/inbox/model/ItemStatus.java
> +package com.global.inbox.model;
What do you mean?

2022-07-18 11:42 UTC, olehkril requested changes

2022-07-18 11:42 UTC, olehkril commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-web'
Marked as done, but you need to push your changes

2022-07-19 08:49 UTC, olehkril requested changes

2022-07-19 08:49 UTC, olehkril commented on build.gradle
> +	implementation group: 'org.springframework', name: 'spring-webflux', version: '5.3.21'
If you have starter, then you don't need spring-webflux seprately.

2022-07-19 08:49 UTC, olehkril commented on build.gradle
> +	//test
test to the bottom

2022-07-19 08:49 UTC, olehkril commented on build.gradle
> +	//lombok
split in sections like following

```
//spring
compile()
compile()

//test
testCompile()
```

2022-07-19 08:49 UTC, olehkril commented on src/main/java/com/global/inbox/controller/ItemsController.java
> +    @GetMapping
new line

2022-07-19 08:49 UTC, olehkril commented on DevOps-local/docker-compose.yaml
> +version: '3.7'
DevOps-local > environment

2022-07-19 08:49 UTC, olehkril commented on DevOps-local/docker-compose.yaml
> +version: '3.7'
Also, you can add some small instruction into `README.md` file. 

## Local usage...

### Prerequisites 

1. Docker
2. Docker compose

In order to run locally... 

`cd environment && docker compose up -d `

2022-07-19 12:28 UTC, olehkril approved these changes

2022-07-19 12:28 UTC, merged